name: Adds all issues that don't include the 'bug' or 'needs-triage' labels to project board

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
        uses: actions/add-to-project@v0.4.1
        with:
          project-url: https://github.com/users/McUsr/projects/2
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          labeled: bug, needs-triage
          label-operator: NOT
